name: Build Python EXE for Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: >
          pyinstaller 
          --onefile 
          --windowed 
          --add-data "config.json;." 
          --name "ShopifyFulfillmentTool" 
          gui_main.py

      - name: List dist folder
        run: dir dist

      - name: Upload EXE to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/ShopifyFulfillmentTool.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
